version: "3"

tasks:
  build:
    desc: Build Go into binary for deployment
    cmds:
      - go build -o app .
  
  start:
    desc: Start database container and run Go app locally
    cmds:
      - docker compose up -d
      - source .env && go run main.go
  
  provision:
    desc: Build docker images
    cmds:
      - docker compose build

  docker:down:
    desc: Stop containers
    cmds:
      - docker compose down
  
  docker:logs:
    desc: Show logs
    cmds:
      - docker compose logs -f
  # this command is used for generating test (MOCK) files for supporting writing test only
  gen-mocks:
    mockery
