// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"url-shortener/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// DecodeUrl provides a mock function for the type MockService
func (_mock *MockService) DecodeUrl(ctx context.Context, input dto.DecodeURLReq) (*dto.DecodeURLResp, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DecodeUrl")
	}

	var r0 *dto.DecodeURLResp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.DecodeURLReq) (*dto.DecodeURLResp, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.DecodeURLReq) *dto.DecodeURLResp); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.DecodeURLResp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.DecodeURLReq) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_DecodeUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecodeUrl'
type MockService_DecodeUrl_Call struct {
	*mock.Call
}

// DecodeUrl is a helper method to define mock.On call
//   - ctx context.Context
//   - input dto.DecodeURLReq
func (_e *MockService_Expecter) DecodeUrl(ctx interface{}, input interface{}) *MockService_DecodeUrl_Call {
	return &MockService_DecodeUrl_Call{Call: _e.mock.On("DecodeUrl", ctx, input)}
}

func (_c *MockService_DecodeUrl_Call) Run(run func(ctx context.Context, input dto.DecodeURLReq)) *MockService_DecodeUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.DecodeURLReq
		if args[1] != nil {
			arg1 = args[1].(dto.DecodeURLReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_DecodeUrl_Call) Return(decodeURLResp *dto.DecodeURLResp, err error) *MockService_DecodeUrl_Call {
	_c.Call.Return(decodeURLResp, err)
	return _c
}

func (_c *MockService_DecodeUrl_Call) RunAndReturn(run func(ctx context.Context, input dto.DecodeURLReq) (*dto.DecodeURLResp, error)) *MockService_DecodeUrl_Call {
	_c.Call.Return(run)
	return _c
}

// EncodeUrl provides a mock function for the type MockService
func (_mock *MockService) EncodeUrl(ctx context.Context, input dto.EncodeURLReq) (*dto.EncodeURLResp, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for EncodeUrl")
	}

	var r0 *dto.EncodeURLResp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.EncodeURLReq) (*dto.EncodeURLResp, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.EncodeURLReq) *dto.EncodeURLResp); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.EncodeURLResp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.EncodeURLReq) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_EncodeUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncodeUrl'
type MockService_EncodeUrl_Call struct {
	*mock.Call
}

// EncodeUrl is a helper method to define mock.On call
//   - ctx context.Context
//   - input dto.EncodeURLReq
func (_e *MockService_Expecter) EncodeUrl(ctx interface{}, input interface{}) *MockService_EncodeUrl_Call {
	return &MockService_EncodeUrl_Call{Call: _e.mock.On("EncodeUrl", ctx, input)}
}

func (_c *MockService_EncodeUrl_Call) Run(run func(ctx context.Context, input dto.EncodeURLReq)) *MockService_EncodeUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.EncodeURLReq
		if args[1] != nil {
			arg1 = args[1].(dto.EncodeURLReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_EncodeUrl_Call) Return(encodeURLResp *dto.EncodeURLResp, err error) *MockService_EncodeUrl_Call {
	_c.Call.Return(encodeURLResp, err)
	return _c
}

func (_c *MockService_EncodeUrl_Call) RunAndReturn(run func(ctx context.Context, input dto.EncodeURLReq) (*dto.EncodeURLResp, error)) *MockService_EncodeUrl_Call {
	_c.Call.Return(run)
	return _c
}
