// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"url-shortener/internal/model"
	"url-shortener/internal/repository/urlshortener"

	mock "github.com/stretchr/testify/mock"
)

// NewMockURLShortenerRepository creates a new instance of MockURLShortenerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLShortenerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLShortenerRepository {
	mock := &MockURLShortenerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockURLShortenerRepository is an autogenerated mock type for the URLShortenerRepository type
type MockURLShortenerRepository struct {
	mock.Mock
}

type MockURLShortenerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLShortenerRepository) EXPECT() *MockURLShortenerRepository_Expecter {
	return &MockURLShortenerRepository_Expecter{mock: &_m.Mock}
}

// FindOne provides a mock function for the type MockURLShortenerRepository
func (_mock *MockURLShortenerRepository) FindOne(input repository.FindOneInput) (*model.URLShortener, error) {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for FindOne")
	}

	var r0 *model.URLShortener
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(repository.FindOneInput) (*model.URLShortener, error)); ok {
		return returnFunc(input)
	}
	if returnFunc, ok := ret.Get(0).(func(repository.FindOneInput) *model.URLShortener); ok {
		r0 = returnFunc(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.URLShortener)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(repository.FindOneInput) error); ok {
		r1 = returnFunc(input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockURLShortenerRepository_FindOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOne'
type MockURLShortenerRepository_FindOne_Call struct {
	*mock.Call
}

// FindOne is a helper method to define mock.On call
//   - input repository.FindOneInput
func (_e *MockURLShortenerRepository_Expecter) FindOne(input interface{}) *MockURLShortenerRepository_FindOne_Call {
	return &MockURLShortenerRepository_FindOne_Call{Call: _e.mock.On("FindOne", input)}
}

func (_c *MockURLShortenerRepository_FindOne_Call) Run(run func(input repository.FindOneInput)) *MockURLShortenerRepository_FindOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 repository.FindOneInput
		if args[0] != nil {
			arg0 = args[0].(repository.FindOneInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockURLShortenerRepository_FindOne_Call) Return(uRLShortener *model.URLShortener, err error) *MockURLShortenerRepository_FindOne_Call {
	_c.Call.Return(uRLShortener, err)
	return _c
}

func (_c *MockURLShortenerRepository_FindOne_Call) RunAndReturn(run func(input repository.FindOneInput) (*model.URLShortener, error)) *MockURLShortenerRepository_FindOne_Call {
	_c.Call.Return(run)
	return _c
}

// GetNextID provides a mock function for the type MockURLShortenerRepository
func (_mock *MockURLShortenerRepository) GetNextID(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetNextID")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockURLShortenerRepository_GetNextID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNextID'
type MockURLShortenerRepository_GetNextID_Call struct {
	*mock.Call
}

// GetNextID is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockURLShortenerRepository_Expecter) GetNextID(ctx interface{}) *MockURLShortenerRepository_GetNextID_Call {
	return &MockURLShortenerRepository_GetNextID_Call{Call: _e.mock.On("GetNextID", ctx)}
}

func (_c *MockURLShortenerRepository_GetNextID_Call) Run(run func(ctx context.Context)) *MockURLShortenerRepository_GetNextID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockURLShortenerRepository_GetNextID_Call) Return(n int64, err error) *MockURLShortenerRepository_GetNextID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockURLShortenerRepository_GetNextID_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockURLShortenerRepository_GetNextID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMapping provides a mock function for the type MockURLShortenerRepository
func (_mock *MockURLShortenerRepository) UpdateMapping(input repository.UpdateMappingInput) error {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMapping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(repository.UpdateMappingInput) error); ok {
		r0 = returnFunc(input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockURLShortenerRepository_UpdateMapping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMapping'
type MockURLShortenerRepository_UpdateMapping_Call struct {
	*mock.Call
}

// UpdateMapping is a helper method to define mock.On call
//   - input repository.UpdateMappingInput
func (_e *MockURLShortenerRepository_Expecter) UpdateMapping(input interface{}) *MockURLShortenerRepository_UpdateMapping_Call {
	return &MockURLShortenerRepository_UpdateMapping_Call{Call: _e.mock.On("UpdateMapping", input)}
}

func (_c *MockURLShortenerRepository_UpdateMapping_Call) Run(run func(input repository.UpdateMappingInput)) *MockURLShortenerRepository_UpdateMapping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 repository.UpdateMappingInput
		if args[0] != nil {
			arg0 = args[0].(repository.UpdateMappingInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockURLShortenerRepository_UpdateMapping_Call) Return(err error) *MockURLShortenerRepository_UpdateMapping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockURLShortenerRepository_UpdateMapping_Call) RunAndReturn(run func(input repository.UpdateMappingInput) error) *MockURLShortenerRepository_UpdateMapping_Call {
	_c.Call.Return(run)
	return _c
}
